package edu.iastate.cs362.project;

import java.io.File;

import javax.swing.JOptionPane;

public class AdminFrontPage extends javax.swing.JFrame {
	
	private BankController controller;
    /**
     * Creates new form AdminFrontPage
     */
    public AdminFrontPage() {
    	File file = new File("Database.bankdata");
		controller = new BankController(file);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        homeTab = new javax.swing.JPanel();
        labelname = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        buttonLoanApprov = new javax.swing.JButton();
        buttonUnlock = new javax.swing.JButton();
        buttonLock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelname.setText("Name:");

        name.setText("-");

        buttonLoanApprov.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonLoanApprov.setText("Approve Loan");
        buttonLoanApprov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLoanApprovMouseClicked(evt);
            }
        });

        buttonUnlock.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonUnlock.setText("Unlock Account");
        buttonUnlock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonUnlockMouseClicked(evt);
            }
        });

        buttonLock.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonLock.setText("Lock Account");
        buttonLock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLockMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout homeTabLayout = new javax.swing.GroupLayout(homeTab);
        homeTab.setLayout(homeTabLayout);
        homeTabLayout.setHorizontalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeTabLayout.createSequentialGroup()
                        .addComponent(labelname)
                        .addGap(28, 28, 28)
                        .addComponent(name)
                        .addGap(24, 322, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeTabLayout.createSequentialGroup()
                        .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonLock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonUnlock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonLoanApprov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        homeTabLayout.setVerticalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelname)
                    .addComponent(name))
                .addGap(18, 18, 18)
                .addComponent(buttonLock, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonUnlock, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonLoanApprov, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Home", homeTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoanApprovMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLoanApprovMouseClicked
    	String username = (String)JOptionPane.showInputDialog(
                "UserName:");
    	if(username != null)
    	{
    		Main.controller.approveLoan(username);
    	}
    }//GEN-LAST:event_buttonLoanApprovMouseClicked

    private void buttonUnlockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonUnlockMouseClicked
    	String user = (String)(String)JOptionPane.showInputDialog(
                "Enter username:");
    	String acc = (String)JOptionPane.showInputDialog(
                "Enter account to unlock:");
    	if(acc != null && user != null)
    	{
    		Main.controller.unlockAccount(user + "-" + acc);
    	}
    }//GEN-LAST:event_buttonUnlockMouseClicked

    private void buttonLockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLockMouseClicked
    	String user = (String)(String)JOptionPane.showInputDialog(
                "Enter username:");
    	String acc = (String)JOptionPane.showInputDialog(
                "Enter account to lock:");
    	if(acc != null && user != null)
    	{
    		Main.controller.lockAccount(user + "-" + acc);
    	}
    }//GEN-LAST:event_buttonLockMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void startApp() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrontPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLoanApprov;
    private javax.swing.JButton buttonLock;
    private javax.swing.JButton buttonUnlock;
    private javax.swing.JPanel homeTab;
    private javax.swing.JLabel labelname;
    private javax.swing.JLabel name;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
