package edu.iastate.cs362.project;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class FrontPage extends javax.swing.JFrame {
	
	User loggedUser;
	List<Account> loggedAccounts = new ArrayList<Account>();
	ArrayList<AccountTab> tabs = new ArrayList<AccountTab>();

    /**
     * Creates new form FrontPage
     */
    public FrontPage() {
    	loggedUser = Main.controller.getLoginUser();
    	loggedAccounts = loggedUser.getAccounts();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton4 = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        homeTab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        totalBalance = new javax.swing.JLabel();
        pNumber = new javax.swing.JLabel();
        nameOfUser = new javax.swing.JLabel();
        buttonAccount = new javax.swing.JButton();
        buttonPass = new javax.swing.JButton();
        buttonPNum = new javax.swing.JButton();
        lockStatus = new javax.swing.JLabel();
        buttonTransfer = new javax.swing.JButton();
        buttonLoanReq = new javax.swing.JButton();
        buttonFixedDep = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTextPane1);

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name:");

        jLabel2.setText("Phone Number:");

        jLabel3.setText("Total Balance:");

        totalBalance.setText("-");

        pNumber.setText("-");

        nameOfUser.setText("-");

        buttonAccount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonAccount.setText("Add Account");
        buttonAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAccountMouseClicked(evt);
            }
        });

        buttonPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonPass.setText("Change Password");
        buttonPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPassMouseClicked(evt);
            }
        });

        buttonPNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonPNum.setText("Change Phone Number");
        buttonPNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPNumMouseClicked(evt);
            }
        });

        lockStatus.setForeground(new java.awt.Color(255, 51, 51));
        lockStatus.setText("-");

        buttonTransfer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonTransfer.setText("Transfer Money");
        buttonTransfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonTransferMouseClicked(evt);
            }
        });

        buttonLoanReq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonLoanReq.setText("Request Loan");
        buttonLoanReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLoanReqMouseClicked(evt);
            }
        });

        buttonFixedDep.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonFixedDep.setText("Fixed Deposit");
        buttonFixedDep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonFixedDepMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout homeTabLayout = new javax.swing.GroupLayout(homeTab);
        homeTab.setLayout(homeTabLayout);
        homeTabLayout.setHorizontalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeTabLayout.createSequentialGroup()
                        .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pNumber)
                            .addComponent(totalBalance)
                            .addComponent(nameOfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                        .addComponent(lockStatus)
                        .addGap(24, 24, 24))
                    .addGroup(homeTabLayout.createSequentialGroup()
                        .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonPNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(buttonAccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(buttonLoanReq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonFixedDep, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                        .addGap(3, 3, 3))))
        );
        homeTabLayout.setVerticalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeTabLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nameOfUser)))
                    .addGroup(homeTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lockStatus)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pNumber))
                .addGap(14, 14, 14)
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(totalBalance))
                .addGap(34, 34, 34)
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPNum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFixedDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonLoanReq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPass, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabbedPane.addTab("Home", homeTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setText(loggedUser.getName());
        

        pNumber.setText(Main.controller.getLoginUser().getPhoneNumber());
        
        for(Account acc : loggedAccounts)
        {
        	AccountTab tab = new AccountTab(acc.getAccountID(), this); 
        	tabbedPane.addTab(acc.getAccountID(), tab);
        	if(acc.checkLockStatus())
        	{
        		tabbedPane.setEnabledAt(tabbedPane.getTabCount()-1, false);
        		String tooltip = "Closed Account!";
        		tabbedPane.setToolTipTextAt(tabbedPane.getTabCount()-1, tooltip);
        	}
        	tabs.add(tab);
        }
        
        updateTotal();
        
        pack();
    }// </editor-fold>                        

    private void buttonAccountMouseClicked(java.awt.event.MouseEvent evt) {                                           
    	Main.controller.createAccount(loggedUser.getUsername());   
    	loggedAccounts = loggedUser.getAccounts();
    	String accountID = loggedAccounts.get(loggedAccounts.size()-1).getAccountID();
    	AccountTab tab = new AccountTab(accountID, this);
    	tabs.add(tab);
        tabbedPane.addTab(accountID, tab);
    }                                          

    private void buttonPNumMouseClicked(java.awt.event.MouseEvent evt) {                                        
    	String num = (String)JOptionPane.showInputDialog(
                "Update Phone Number (Must be 10 digits):");
    	if(num != null && num.length() == 10)
    	{
    		Main.controller.updatePhoneNumber(loggedUser.getUsername(), num);    	
    		pNumber.setText(Main.controller.getPhoneNumber(loggedUser.getUsername()));
    	} else {
    		JOptionPane.showMessageDialog(null, "Phonenumber length must be 10 digits");
    	}
    }                                       

    private void buttonTransferMouseClicked(java.awt.event.MouseEvent evt) {                                            
    	String acc1 = (String)JOptionPane.showInputDialog(
                "Enter account to transfer FROM:");
    	String acc2 = (String)JOptionPane.showInputDialog(
                "Enter account to transfer TO:");
    	String amount = (String)JOptionPane.showInputDialog(
                "Enter amount:");
    	if(acc1 != null && acc2 != null && amount != null)
    	{
    		Main.controller.transferMoney(loggedUser.getUsername() + "-" + acc1, 
    				loggedUser.getUsername() + "-" + acc2, Double.valueOf(amount));
    		
    		///Update the text for each text for balances
    		for(AccountTab tab : tabs)
    		{
    			tab.updateBalance();
    		}
    	}
    }                                           

    private void buttonLoanReqMouseClicked(java.awt.event.MouseEvent evt) {                                           
    	String amount = (String)JOptionPane.showInputDialog(
                "Loan amount:");
    	if(amount != null)
    	{
    		Main.controller.requestLoan(loggedUser.getUsername(), Double.valueOf(amount));
    	}
    }                                          

    private void buttonPassMouseClicked(java.awt.event.MouseEvent evt) {                                        
    	String pass = (String)JOptionPane.showInputDialog(
                "Change password: ");
    	if(pass != null)
    	{
	    	if(!Main.controller.changePassword(loggedUser.getUsername(), pass))
	    	{
	    		JOptionPane.showMessageDialog(this,
	    			    "Password change failed.",
	    			    "Error!",
	    			    JOptionPane.ERROR_MESSAGE);
	    	}	    		
    	}
    }                                       

    private void buttonFixedDepMouseClicked(java.awt.event.MouseEvent evt) {                                            
    	String accountID = (String)JOptionPane.showInputDialog(
                "Account id: ");
    	String amount = (String)JOptionPane.showInputDialog(
                "Amount: ");
    	String months = (String)JOptionPane.showInputDialog(
                "Months: ");
    	if(accountID != null && amount != null && months != null)
    	{
    		Main.controller.fixedDeposit(loggedUser.getUsername() + "-" + accountID, Double.valueOf(amount), Integer.valueOf(months));
    		
    		///Update the text for each text for balances
    		for(AccountTab tab : tabs)
    		{
    			tab.updateBalance();
    			updateTotal();
    		}
    	}
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void startApp() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrontPage().setVisible(true);
            }
        });
    }
    
    public void updateTotal()
    {   	
    	totalBalance.setText("$" + new DecimalFormat("#0.00").format(loggedUser.getTotalBalance()));
    }
    
    public void deletePage(String id, String toID)
    {
    	for(int i = 0; i < tabs.size(); ++i)
    	{
    		if(tabs.get(i).id == id)
    		{
    			tabs.get(i).updateBalance();
    			updateTotal();
    			tabbedPane.remove(i+1); // Account for the home tab
    			tabs.remove(i);
    		}
    		if(tabs.get(i).id == toID)
    		{
    			tabs.get(i).updateBalance();
    		}
    	}
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton buttonAccount;
    private javax.swing.JButton buttonFixedDep;
    private javax.swing.JButton buttonLoanReq;
    private javax.swing.JButton buttonPNum;
    private javax.swing.JButton buttonPass;
    private javax.swing.JButton buttonTransfer;
    private javax.swing.JPanel homeTab;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lockStatus;
    private javax.swing.JLabel nameOfUser;
    private javax.swing.JLabel pNumber;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JLabel totalBalance;
    // End of variables declaration                   
}
